version: '3'

volumes:
  cart_redis_volume:

networks:
  default-net:
    driver: bridge
    external: true

services:
  cart_database:
    image: postgres
    networks:
      - default-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - ./cart_database/data:/var/lib/postgresql/data
    ports:
      - 5432

  cart_service:
    build:
      context: ./cart_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./cart_service:/cart_service
    ports:
      - 1006:3000
    links:
      - cart_database
      - cart_redis
      - cart_consumer1
      - cart_consumer2
      - cart_consumer3
      - cart_consumer4
    depends_on:
      - cart_database
      - cart_redis
      - cart_consumer1
      - cart_consumer2
      - cart_consumer3
      - cart_consumer4
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:migrate
        rails server -b 0.0.0.0 -p 3000

  cart_consumer1:
    build:
      context: ./cart_service
      dockerfile: Dockerfile
    networks:
      - default-net
    links:
      - cart_redis
    environment:
      - RAILS_ENV=development
    volumes:
      - ./cart_service:/cart_service
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        bundle exec racecar ProductsConsumer

  cart_consumer2:
    build:
      context: ./cart_service
      dockerfile: Dockerfile
    networks:
      - default-net
    links:
      - cart_redis
    environment:
      - RAILS_ENV=development
    volumes:
      - ./cart_service:/cart_service
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        bundle exec racecar WishlistItemsConsumer

  cart_consumer3:
    build:
      context: ./cart_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./cart_service:/cart_service
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        bundle exec racecar CartItemsRemoveConsumer

  cart_consumer4:
    build:
      context: ./cart_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./cart_service:/cart_service
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        bundle exec racecar TotalItemsConsumer

  cart_redis:
    image: redis:latest
    ports:
      - 6379
    networks:
      - default-net
    volumes:
      - cart_redis_volume:/usr/local/etc/redis
