version: '3'

volumes:
  etcd_volume:

networks:
  default-net:
    driver: bridge
    external: true

# https://github.com/bitnami/bitnami-docker-etcd
services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - etcd_volume:/bitnami/etcd
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - default-net
