version: '3'

networks:
  default-net:
    driver: bridge
    external: true

services:
  freight_database:
    image: postgres
    networks:
      - default-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - ./freight_database/data:/var/lib/postgresql/data
    ports:
      - 5432

  freight_service:
    build:
      context: ./freight_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./freight_service:/freight_service
    ports:
      - 1005:3000
    links:
      - freight_database
    depends_on:
      - freight_database
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:migrate db:seed
        rails server -b 0.0.0.0 -p 3000
