version: '3'

volumes:
  support_redis_volume:

networks:
  default-net:
    driver: bridge
    external: true

services:
  support_database:
    image: postgres
    networks:
      - default-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - ./support_database/data:/var/lib/postgresql/data
    ports:
      - 5432

  support_service:
    build:
      context: ./support_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./support_service:/support_service
    ports:
      - 1003:3000
    links:
      - support_database
      - support_consumer
    depends_on:
      - support_database
      - support_consumer
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:migrate db:seed
        rails server -b 0.0.0.0 -p 3000

  support_consumer:
    build:
      context: ./support_service
      dockerfile: Dockerfile
    networks:
      - default-net
    links:
      - support_redis
    environment:
      - RAILS_ENV=development
    volumes:
      - ./support_service:/support_service
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        bundle exec racecar OrdersConsumer

  support_redis:
    image: redis:latest
    ports:
      - 6379
    networks:
      - default-net
    volumes:
      - support_redis_volume:/usr/local/etc/redis
