version: '3'

volumes:
  product_database_volume:

networks:
  default-net:
    driver: bridge
    external: true

services:
  product_database:
    image: postgres
    networks:
      - default-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - product_database_volume:/var/lib/postgresql/data
    ports:
      - 5432

  product_service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./product_service:/product_service
    ports:
      - 1001:3000
    links:
      - product_database
    depends_on:
      - product_database
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        rails db:migrate db:seed
        rails server -b 0.0.0.0 -p 3000
