version: '3'

volumes:
  freight_database_volume:
  freight_redis_volume:

networks:
  default-net:
    driver: bridge
    external: true

services:
  freight_database:
    image: postgres
    networks:
      - default-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - freight_database_volume:/var/lib/postgresql/data
    ports:
      - 5432

  freight_service:
    build:
      context: ./freight_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./freight_service:/freight_service
    ports:
      - 1005:3000
    links:
      - freight_database
      - freight_consumer
      - freight_redis
    depends_on:
      - freight_database
      - freight_consumer
      - freight_redis
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        rails db:migrate db:seed
        rails server -b 0.0.0.0 -p 3000

  freight_consumer:
    build:
      context: ./freight_service
      dockerfile: Dockerfile
    networks:
      - default-net
    links:
      - freight_redis
    environment:
      - RAILS_ENV=development
    volumes:
      - ./freight_service:/freight_service
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        bundle exec racecar CalculateFreightConsumer

  freight_redis:
    image: redis:latest
    ports:
      - 6379
    networks:
      - default-net
    volumes:
      - freight_redis_volume:/data
