version: '3'

services:
  product_database:
    image: postgres
    user: "${UID}:${GID}"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - ./product_database/data:/var/lib/postgresql/data
    ports:
      - 5432

  product_service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    environment:
      - RAILS_ENV=development
    volumes:
      - ./product_service:/product_service
    ports:
      - 1001:3000
    links:
      - product_database
    depends_on:
      - product_database
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:migrate db:seed
        rails server -b 0.0.0.0 -p 3000

  wishlist_database:
    image: postgres
    user: "${UID}:${GID}"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - ./wishlist_database/data:/var/lib/postgresql/data
    ports:
      - 5432

  wishlist_service:
    build:
      context: ./wishlist_service
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    environment:
      - RAILS_ENV=development
    volumes:
      - ./wishlist_service:/wishlist_service
    ports:
      - 1002:3000
    links:
      - wishlist_database
    depends_on:
      - wishlist_database
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:migrate db:seed
        rails server -b 0.0.0.0 -p 3000

  support_database:
    image: postgres
    user: "${UID}:${GID}"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - ./support_database/data:/var/lib/postgresql/data
    ports:
      - 5432

  support_service:
    build:
      context: ./support_service
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    environment:
      - RAILS_ENV=development
    volumes:
      - ./support_service:/support_service
    ports:
      - 1003:3000
    links:
      - support_database
    depends_on:
      - support_database
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:migrate db:seed
        rails server -b 0.0.0.0 -p 3000

  order_database:
    image: postgres
    user: "${UID}:${GID}"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - ./order_database/data:/var/lib/postgresql/data
    ports:
      - 5432

  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    environment:
      - RAILS_ENV=development
    volumes:
      - ./order_service:/order_service
    ports:
      - 1004:3000
    links:
      - order_database
    depends_on:
      - order_database
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:migrate db:seed
        rails server -b 0.0.0.0 -p 3000
