version: '3'

volumes:
  order_database_volume:
  order_redis_volume:

networks:
  default-net:
    driver: bridge
    external: true

services:
  order_database:
    image: postgres
    networks:
      - default-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - order_database_volume:/var/lib/postgresql/data
    ports:
      - 5432

  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./order_service:/order_service
    ports:
      - 1004:3000
    links:
      - order_database
      - order_redis
      - order_consumer1
      - order_consumer2
      - order_consumer3
    depends_on:
      - order_database
      - order_redis
      - order_consumer1
      - order_consumer2
      - order_consumer3
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:migrate db:seed
        rails server -b 0.0.0.0 -p 3000

  order_consumer1:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    networks:
      - default-net
    links:
      - order_redis
    environment:
      - RAILS_ENV=development
    volumes:
      - ./order_service:/order_service
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        bundle exec racecar CartsConsumer

  order_consumer2:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./order_service:/order_service
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        bundle exec racecar TotalItemsReplyConsumer

  order_consumer3:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    networks:
      - default-net
    environment:
      - RAILS_ENV=development
    volumes:
      - ./order_service:/order_service
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        bundle exec racecar CalculateFreightReplyConsumer

  order_redis:
    image: redis:latest
    ports:
      - 6379
    networks:
      - default-net
    volumes:
      - order_redis_volume:/data
