swagger: '2.0'
info:
  version: '1.0.0'
  title: 'freight_service'

host: 'localhost:1005'

schemes:
  - 'http'

definitions:
  Freight:
    type: object
    properties:
      calculate:
        type: object
        properties:
          total_price:
            description: Preço total do pedido
            type: number
            example: 56.60
          total_items:
            description: Total de itens no pedido
            type: integer
            example: 126
          zip_code:
            description: CEP de entrega
            type: integer
            example: 12512000

paths:
  /freights/calculate:
    post:
      tags:
        - 'Freights'
      summary: Calcula o valor do frete
      description: Calcula o valor do frete com base na quantidade de itens e no valor total do pedido.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: layout
          required: true
          schema:
            $ref: '#/definitions/Freight'

      responses:
        200:
          description: Retorna o frete calculado
          schema:
            type: object
            properties:
              freight_price:
                description: Preço do frete calculado
                type: number
                example: 13.63
