swagger: '2.0'
info:
  version: '1.0.0'
  title: 'order_service'

host: 'localhost:1004'

schemes:
  - 'http'

definitions:
  OpenOrder:
    type: object
    properties:
      id:
        type: integer
        description: Identificador único.
      attributes:
        type: object
        properties:
          status: &order_status
            description: Status do pedido
            type: string
            example: open
          client_id: &order_client_id
            description: Id do cliente associado
            type: integer
            example: 100
          item_ids: &order_item_ids
            description: Itens associados ao pedido aberto
            type: array
            example: [101,102,323]
          created_at: &order_created_at
            type: string
            format: date-time
            example: '2020-01-23 02:09:06 -0300'
          updated_at: &order_updated_at
            type: string
            format: date-time
            example: '2020-01-23 02:09:06 -0300'

  ClosedOrder:
    type: object
    properties:
      id:
        type: integer
        description: Identificador único.
      attributes:
        type: object
        properties:
          status:
            description: Status da ordem
            type: string
            example: closed
          client_id: *order_client_id
          item_ids: *order_item_ids
          created_at: *order_created_at
          updated_at: *order_updated_at

paths:
  /orders/{id}:
    parameters:
      - in: path
        name: id
        required: true
        type: integer

    get:
      tags:
        - 'Open Orders'
        - 'Closed Orders'
      summary: Exibe um pedido
      description: Exibe um pedido e seus atributos
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Retorna os detalhes de um pedido
          schema:
            $ref: '#/definitions/OpenOrder'

  /orders/open:
    get:
      tags:
        - 'Open Orders'
      summary: Lista de pedidos em aberto
      description: |
        Lista os pedidos em aberto, com diversas possibilidades de filtros usando o ransack (https://github.com/activerecord-hackery/ransack)
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: q[client_id_eq]
          type: integer
          default: 100
          description: Exemplo de um filtro ransack que filtra os pedidos em aberto do cliente com id 100
      responses:
        200:
          description: Retorna uma lista de pedidos em aberto
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/OpenOrder'

    post:
      tags:
        - 'Open Orders'
      summary: Cria um pedido
      description: Cria um pedido e seus detalhes.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: layout
          required: true
          schema:
            type: object
            properties:
              order:
                type: object
                properties:
                  client_id: *order_client_id
                  item_ids: *order_item_ids

      responses:
        201: &order_post_response
          description: Retorna o pedido criado
          schema:
            $ref: '#/definitions/OpenOrder'

        204: *order_post_response
        200: *order_post_response

  /orders/closed:
    get:
      tags:
        - 'Closed Orders'
      summary: Lista de pedidos encerrados
      description: |
        Lista os pedidos encerrados, com diversas possibilidades de filtros usando o ransack (https://github.com/activerecord-hackery/ransack)
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: q[client_id_eq]
          type: integer
          default: 100
          description: Exemplo de um filtro ransack que filtra os pedidos encerrados do cliente com id 100
      responses:
        200:
          description: Retorna uma lista de pedidos encerrados
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/ClosedOrder'

    post:
      tags:
        - 'Closed Orders'
      summary: Encerra um pedido em aberto
      description: Encerra um pedido em aberto e seus detalhes.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: layout
          required: true
          schema:
            type: object
            properties:
              order:
                type: object
                properties:
                  id:
                    description: Id do pedido em aberto
                    type: integer
                    example: 10

      responses:
        422:
          description: Retorna uma mensagem quando não é encontrato uma ordem aberta para ser encerrada
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Order not found'

        201: &order_post_response
          description: Retorna o pedido encerrado
          schema:
            $ref: '#/definitions/ClosedOrder'

        204: *order_post_response
        200: *order_post_response
