swagger: '2.0'
info:
  version: '1.0.0'
  title: 'support_service'

host: 'localhost:1003'

schemes:
  - 'http'

definitions:
  OpenTicket:
    type: object
    properties:
      id:
        type: integer
        description: Identificador único.
      attributes:
        type: object
        properties:
          status: &ticket_status
            description: Status do ticket
            type: string
            example: open
          description: &ticket_description
            description: Descrição do problema
            type: string
            example: Problema X Y Z
          client_id: &ticket_client_id
            description: Id do cliente associado
            type: integer
            example: 100
          created_at: &ticket_created_at
            type: string
            format: date-time
            example: '2020-01-23 02:09:06 -0300'
          updated_at: &ticket_updated_at
            type: string
            format: date-time
            example: '2020-01-23 02:09:06 -0300'

  ClosedTicket:
    type: object
    properties:
      id:
        type: integer
        description: Identificador único.
      attributes:
        type: object
        properties:
          status:
            description: Status do ticket
            type: string
            example: closed
          description: *ticket_description
          client_id: *ticket_client_id
          created_at: *ticket_created_at
          updated_at: *ticket_updated_at

paths:
  /wishlists/open:
    get:
      tags:
        - 'Open Tickets'
      summary: Lista de chamados em aberto
      description: |
        Lista os chamados em aberto, com diversas possibilidades de filtros usando o ransack (https://github.com/activerecord-hackery/ransack)
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: q[client_id_eq]
          type: integer
          default: 100
          description: Exemplo de um filtro ransack que filtra os chamados em aberto do cliente com id 100
      responses:
        200:
          description: Retorna uma lista de chamados em aberto
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/OpenTicket'

    post:
      tags:
        - 'Open Tickets'
      summary: Cria um chamado
      description: Cria um chamado e seus detalhes.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: layout
          required: true
          schema:
            type: object
            properties:
              ticket:
                type: object
                properties:
                  description: *ticket_description
                  client_id: *ticket_client_id

      responses:
        201: &ticket_post_response
          description: Retorna uma lista de chamados em aberto
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/OpenTicket'

        204: *ticket_post_response

  /wishlists/closed:
    get:
      tags:
        - 'Closed Tickets'
      summary: Lista de chamados encerrados
      description: |
        Lista os chamados encerrados, com diversas possibilidades de filtros usando o ransack (https://github.com/activerecord-hackery/ransack)
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: q[client_id_eq]
          type: integer
          default: 100
          description: Exemplo de um filtro ransack que filtra os chamados encerrados do cliente com id 100
      responses:
        200:
          description: Retorna uma lista de chamados encerrados
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/ClosedTicket'

    post:
      tags:
        - 'Closed Tickets'
      summary: Encerra um chamado em aberto
      description: Encerra um chamado em aberto e seus detalhes.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: layout
          required: true
          schema:
            type: object
            properties:
              ticket:
                type: object
                properties:
                  id:
                    description: Id do chamado em aberto
                    type: integer
                    example: 10


      responses:
        201: &ticket_post_response
          description: Retorna uma lista de chamados encerrados
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/ClosedTicket'

        204: *ticket_post_response
